version: '3.5'

services:
  frontend:
    image: ml-frontend
    ports:
      - 3000:3000

  backend:
    image: ml-backend
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    depends_on:
      - training

  training:
    image: ml-training
    volumes:
      - imgs:/src/imgs
      - model:/src/model

volumes:
  model:
  imgs:
