version: '3.5'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000

  backend:
    image: backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db
    depends_on:
      - db

  redis:
    image: redis

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA=/dbdata
    volumes:
      - /usr/app/db:/dbdata

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - /usr/app/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

